### PR TITLE
Clean-up some maze files

### PR DESCRIPTION
**Pull request by Peque**
- Fix a blank file with an invalid format.
- Remove all duplicate files (at least those I was able to recognize as valid duplicates).
- Add Python script used to remove the duplicates.

I can edit the pull-request and remove any of those changes if you would rather not include all of them.

### CODE REVIEW

**Comment by micromouseonline** [comment]
Good job on the duplicate finder.

Some of the duplicates are there because the mazes were used in more than one event.

I have run your Python script against the files I have here and removed the actual duplicates.

Also, I removed the blank training maze because it is pointless. empty.maz is the default starting maze.

Since the duplicates I removed probably differ from yours, can you look at the current master on github and see if the changes I have made satisfy your pull request requirements.

Sorry to do it this way but I am not too familiar with using the Github site and I could not see how to merge in just some of the commits while leaving others alone.


Peter Harrison
peter.harrison@helicron.net

**Comment by micromouseonline** [comment]
Also, I try to remember to make all changes in the develop branch. Things are a bit of a mess right now but it generally works out better if development is done only in develop.

Peter Harrison
peter.harrison@helicron.net

**Comment by Peque** [comment]
Yeah, looks good, we deleted different files because it seems we prefer different name styles, but changes are essentially the same.

If you prefer, next time you want to exclude some commits from a pull-request, just tell me which, it takes me no time to update the pull-request. Or just do it like you did it this time, whatever takes less time for you. :blush:

About the `develop` branch, I will try to remember that for future pull-requests. [I am not used to that](https://softwareengineering.stackexchange.com/questions/312022/the-trend-of-the-develop-branch-going-away). :wink:

However, if you want to keep the `develop` branch you might want to [set it as the default branch in the repository](https://help.github.com/articles/setting-the-default-branch/).

**Comment by micromouseonline** [comment]
Thank you.

I try and stick to the gitflow model for development work. Mostly because Sourcetree has built-in support for it and I like easy-to-use stuff.


I do need to play some more with Github to see how best to handle pull requests and such though.

The extra txt maze is now gone from the binary folder.


> On 18 Mar 2018, at 15:10, Miguel Sánchez de León Peque <notifications@github.com> wrote:
> 
> Yeah, looks good, we deleted different files because it seems we prefer different name styles, but changes are essentially the same.
> 
> If you prefer, next time you want to exclude some commits from a pull-request, just tell me which, it takes me no time to update the pull-request. Or just do it like you did it this time, whatever takes less time for you. 😊
> 
> About the develop branch, I will try to remember that for future pull-requests. I am not used to that. 😉
> 
> However, if you want to keep the develop branch you might want to set it as the default branch in the repository.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Peter Harrison
peter.harrison@helicron.net

**Pull request closed without merging**
